# Generated by Django 4.0.1 on 2022-01-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('task', models.TextField()),
                ('branch', models.PositiveSmallIntegerField(choices=[(0, 'todo'), (1, 'potencjalne błedy użytkownika'), (2, 'znalezione błędy'), (3, 'usprawnienia'), (4, 'CSS')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timeneed', models.IntegerField()),
                ('timedone', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weight', models.PositiveSmallIntegerField(choices=[(0, 'Minor'), (1, 'Major'), (2, 'Critical')], default=0)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'In progress'), (2, 'Done')], default=0)),
                ('timeusing', models.IntegerField(blank=True, default=0)),
                ('projekt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.projects')),
            ],
        ),
    ]
